<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text14_text14</name>
   <tag></tag>
   <elementGuidId>c2b5a1d2-c853-476f-a8a2-bfdb405c953f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1ca5dc5-5e7d-436a-a694-c7607575e8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3af2a3d-72ab-4474-a8dd-db9ab55e9b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text14</value>
      <webElementGuid>e8bd9081-a3a5-4a2b-b5f1-8a5cc6e76fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text14&quot;)</value>
      <webElementGuid>d06240e0-4bbc-4106-8ee8-f9a6fc4cc658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text14']</value>
      <webElementGuid>3b1a2d55-18bb-4c7f-89a4-974d5b524f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[14]</value>
      <webElementGuid>7819884e-2435-4914-920b-3109f9ecfd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text14']</value>
      <webElementGuid>761d11c2-4e63-4d2d-a306-c31aa3a49e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
