<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text35_text35</name>
   <tag></tag>
   <elementGuidId>4a2a1c46-acac-4578-bb91-7abbd0b334b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c24bdd32-7ddc-4e16-b635-bb78b290c256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67225fb0-c85a-4c17-a3f0-25d371e3f948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text35</value>
      <webElementGuid>ae6ea6ff-88df-49d5-981a-589274c641b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text35&quot;)</value>
      <webElementGuid>e5c4f53e-6c50-4cbc-a277-594ec8e4a58b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text35']</value>
      <webElementGuid>0dd6dede-282c-456a-80a0-fe8c2635654e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[35]</value>
      <webElementGuid>f0ef963a-d70c-47d6-98d4-2fe45cd27ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text35']</value>
      <webElementGuid>5b642de4-b794-49b9-ae13-46e1dee0a182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
