<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text21_text21</name>
   <tag></tag>
   <elementGuidId>8f931504-71b6-4bc8-b0b3-42625840eec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>194485d2-5b0b-4799-9a97-ec28e4dd11f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>920d2eb0-2bca-4e9f-a406-b7aae5480939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text21</value>
      <webElementGuid>3bc012cc-87bf-41cc-84e7-22a3f8bdf38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text21&quot;)</value>
      <webElementGuid>1f83cf36-add8-4678-9556-f62acf1331f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text21']</value>
      <webElementGuid>dd9edd12-835a-49a4-babe-07d4765ef918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[21]</value>
      <webElementGuid>5f82aa36-e19c-42d3-aa06-7e2db12a4775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text21']</value>
      <webElementGuid>421a9508-3c0b-42d5-a35e-941979a28604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
