<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text37_text37</name>
   <tag></tag>
   <elementGuidId>b806814a-58ac-4950-9f52-3d99dace811e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text37']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text37</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6af9a53a-a410-452c-aa6e-a6f5684f102c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dce0d89b-7f3c-4d05-831a-193141ac04a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text37</value>
      <webElementGuid>87fde965-d39d-4afa-8bb8-36145f6eaa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text37&quot;)</value>
      <webElementGuid>88c8679f-6fef-46e8-a48b-9ee19e745820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text37']</value>
      <webElementGuid>99dde8ed-919d-4f58-b7fd-c0080422cbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[37]</value>
      <webElementGuid>84bf2ace-d8ca-48f3-b4d0-7c4593acb187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text37']</value>
      <webElementGuid>453504a3-3d70-494d-b3c8-db85955afe63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
