<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio2_radio3</name>
   <tag></tag>
   <elementGuidId>0127f63d-3372-4282-a43d-c5c1eafcc705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1a167f1-713f-4f52-8de0-bb1843ab29a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1d4c8083-fd96-46a1-b934-60a2092c90e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio3</value>
      <webElementGuid>06f1a134-806d-410b-bff5-b01f5c1ec37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio3</value>
      <webElementGuid>eaf2f187-b5a5-497a-8d3f-792442a6d122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio3&quot;)</value>
      <webElementGuid>4729b126-4e41-4e2e-96fd-23ae331d9a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio3']</value>
      <webElementGuid>d6b7ef36-ef70-46c7-a376-fc5da521f2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[23]</value>
      <webElementGuid>99191dba-2e94-43eb-8335-3e54b44eb89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio3']</value>
      <webElementGuid>ffbdec9a-6648-4ce5-af4b-2cd48c53ff25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
