<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio3_radio4</name>
   <tag></tag>
   <elementGuidId>b5edfcfd-50e9-4a79-bca4-fd540e3d0ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f44ea0b2-5180-4731-856b-388ebd437b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b173604e-d320-4236-9e03-dca255fde761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio4</value>
      <webElementGuid>1bd1326d-aef7-4ab8-a889-70ba3d5b9451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio4</value>
      <webElementGuid>bf0714d2-1fc2-40b8-8772-dbd94bc803cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio4&quot;)</value>
      <webElementGuid>d15c9657-b7e8-4525-93d8-b60ec0d781be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio4']</value>
      <webElementGuid>4cc7b8bf-bf67-48b5-8a49-1f2fb70227a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[24]</value>
      <webElementGuid>586243ea-abb3-45a1-8815-d45b7a3b7c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio4']</value>
      <webElementGuid>4e098692-b3ac-4f1b-ba42-181560a9ab06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
